# Generated by Django 6.0.4 on 2026-04-28 11:55

import django.db.models.deletion
import django.db.models.functions.text
import tinymce.models
import utils.database.slug
import utils.database.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": [django.db.models.functions.text.Lower("name"), "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uix_cat_low_name",
                        violation_error_code="unique",
                        violation_error_message="This Category exists already.",
                    )
                ],
            },
            bases=(utils.database.slug.SlugCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uix_platform_low_name",
                        violation_error_code="unique",
                        violation_error_message="This Platform exists already.",
                    )
                ],
            },
            bases=(utils.database.slug.SlugCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="journal.platform",
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("title"), "pk"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("PB", "Published")],
                        default="DF",
                        max_length=2,
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        validators=[utils.database.validators.validate_not_blank]
                    ),
                ),
                ("published", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category_journals",
                        to="journal.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_journals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "links",
                    models.ManyToManyField(
                        blank=True, related_name="link_journals", to="journal.link"
                    ),
                ),
            ],
            options={
                "ordering": ["-published", "-created"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("name"),
                        models.F("active"),
                        name="idx_journal_name_active",
                    ),
                    models.Index(
                        fields=["active", "status", "-published"],
                        name="idx_journal_active_status_pub",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uq_journal_name",
                        violation_error_code="unique",
                        violation_error_message="An Journal with that name exists already.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "PB"), _negated=True),
                            ("published__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_journal_published_has_date",
                        violation_error_code="check",
                        violation_error_message="A published journal must have a publish data.",
                    ),
                ],
            },
            bases=(utils.database.slug.SlugCreateMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="link",
            index=models.Index(
                fields=["active", "platform"], name="idx_link_active_platform"
            ),
        ),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.UniqueConstraint(
                fields=("platform", "url"),
                name="link_platform_url_unique",
                violation_error_code="unique",
                violation_error_message="This Link exists already.",
            ),
        ),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                models.F("platform"),
                name="uix_link_low_title_platform",
                violation_error_code="unique",
                violation_error_message="The title has to be unique per platform.",
            ),
        ),
    ]
