# Generated by Django 6.0.4 on 2026-05-02 13:38

import django.db.models.deletion
import django.db.models.functions.text
import tinymce.models
import utils.database.slug
import utils.database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name"), "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uq_platform_low_name",
                        violation_error_code="unique",
                        violation_error_message="This Platform exists already.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                (
                    "panel",
                    models.CharField(
                        choices=[("JOURNAL", "Journal"), ("PROJECT", "Project")],
                        default="JOURNAL",
                        max_length=7,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="journal.platform",
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("title"), "pk"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("PB", "Published")],
                        default="DF",
                        max_length=2,
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        validators=[utils.database.validators.validate_not_blank]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BLOG", "blog"),
                            ("EPIC_EVENTS", "epic-events"),
                            ("JOURNAL", "journal"),
                            ("OC_LETTINGS", "oc-lettings"),
                            ("PORTFOLIO", "portfolio"),
                            ("SOFT_DESK", "soft-desk"),
                        ],
                        max_length=11,
                    ),
                ),
                ("published", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "links",
                    models.ManyToManyField(
                        blank=True, related_name="link_journals", to="journal.link"
                    ),
                ),
            ],
            options={
                "ordering": ["-published", "-created"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("name"),
                        models.F("active"),
                        name="idx_journal_name_active",
                    ),
                    models.Index(
                        fields=["active", "status", "-published"],
                        name="idx_journal_active_status_pub",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uq_journal_name",
                        violation_error_code="unique",
                        violation_error_message="A Journal with that name exists already.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "PB"), _negated=True),
                            ("published__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_journal_published_has_date",
                        violation_error_code="check",
                        violation_error_message="A published journal must have a publish date.",
                    ),
                ],
            },
            bases=(utils.database.slug.SlugCreateMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="link",
            index=models.Index(
                fields=["active", "platform"], name="idx_link_active_platform"
            ),
        ),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.UniqueConstraint(
                fields=("platform", "url"),
                name="link_platform_url_unique",
                violation_error_code="unique",
                violation_error_message="This Link exists already.",
            ),
        ),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                models.F("platform"),
                name="uix_link_title_platform",
                violation_error_code="unique",
                violation_error_message="The title has to be unique per platform.",
            ),
        ),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.CheckConstraint(
                condition=models.Q(("panel__in", ["JOURNAL", "PROJECT"])),
                name="ck_link_panel",
                violation_error_code="check",
                violation_error_message="Panel choice does not exist.",
            ),
        ),
    ]
