# Generated by Django 5.0.6 on 2024-08-03 20:49

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doridoro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("legend", models.CharField(blank=True, max_length=100, null=True)),
                ("legend_en", models.CharField(blank=True, max_length=100, null=True)),
                ("legend_de", models.CharField(blank=True, max_length=100, null=True)),
                ("legend_fr", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("GITHUB", "GitHub"),
                            ("VERCEL", "Vercel"),
                            ("RENDER", "Render"),
                            ("OTHER", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "origin_en",
                    models.CharField(
                        choices=[
                            ("GITHUB", "GitHub"),
                            ("VERCEL", "Vercel"),
                            ("RENDER", "Render"),
                            ("OTHER", "Other"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "origin_de",
                    models.CharField(
                        choices=[
                            ("GITHUB", "GitHub"),
                            ("VERCEL", "Vercel"),
                            ("RENDER", "Render"),
                            ("OTHER", "Other"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "origin_fr",
                    models.CharField(
                        choices=[
                            ("GITHUB", "GitHub"),
                            ("VERCEL", "Vercel"),
                            ("RENDER", "Render"),
                            ("OTHER", "Other"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("OPENCLASSROOMS", "OpenClasssrooms"),
                            ("PERSONAL_PROJECT", "Personal Project"),
                        ],
                        max_length=17,
                    ),
                ),
                (
                    "platform_en",
                    models.CharField(
                        choices=[
                            ("OPENCLASSROOMS", "OpenClasssrooms"),
                            ("PERSONAL_PROJECT", "Personal Project"),
                        ],
                        max_length=17,
                        null=True,
                    ),
                ),
                (
                    "platform_de",
                    models.CharField(
                        choices=[
                            ("OPENCLASSROOMS", "OpenClasssrooms"),
                            ("PERSONAL_PROJECT", "Personal Project"),
                        ],
                        max_length=17,
                        null=True,
                    ),
                ),
                (
                    "platform_fr",
                    models.CharField(
                        choices=[
                            ("OPENCLASSROOMS", "OpenClasssrooms"),
                            ("PERSONAL_PROJECT", "Personal Project"),
                        ],
                        max_length=17,
                        null=True,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="link visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROGRAMMING_SKILLS", "Programming Skills"),
                            ("SOFT_SKILLS", "Soft Skills"),
                            ("OTHER", "Other"),
                            ("STRENGTH", "Strength"),
                            ("WEAKNESSES", "Weakness"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category_en",
                    models.CharField(
                        choices=[
                            ("PROGRAMMING_SKILLS", "Programming Skills"),
                            ("SOFT_SKILLS", "Soft Skills"),
                            ("OTHER", "Other"),
                            ("STRENGTH", "Strength"),
                            ("WEAKNESSES", "Weakness"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "category_de",
                    models.CharField(
                        choices=[
                            ("PROGRAMMING_SKILLS", "Programming Skills"),
                            ("SOFT_SKILLS", "Soft Skills"),
                            ("OTHER", "Other"),
                            ("STRENGTH", "Strength"),
                            ("WEAKNESSES", "Weakness"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "category_fr",
                    models.CharField(
                        choices=[
                            ("PROGRAMMING_SKILLS", "Programming Skills"),
                            ("SOFT_SKILLS", "Soft Skills"),
                            ("OTHER", "Other"),
                            ("STRENGTH", "Strength"),
                            ("WEAKNESSES", "Weakness"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="tag visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("title_en", models.CharField(max_length=250, null=True)),
                ("title_de", models.CharField(max_length=250, null=True)),
                ("title_fr", models.CharField(max_length=250, null=True)),
                ("slug", models.SlugField()),
                ("create_date", models.DateField(verbose_name="create date")),
                ("introduction", tinymce.models.HTMLField()),
                ("introduction_en", tinymce.models.HTMLField(null=True)),
                ("introduction_de", tinymce.models.HTMLField(null=True)),
                ("introduction_fr", tinymce.models.HTMLField(null=True)),
                ("content", tinymce.models.HTMLField()),
                ("content_en", tinymce.models.HTMLField(null=True)),
                ("content_de", tinymce.models.HTMLField(null=True)),
                ("content_fr", tinymce.models.HTMLField(null=True)),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="project visible on website"
                    ),
                ),
                (
                    "doridoro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doro_project",
                        to="doridoro.doridoro",
                    ),
                ),
                (
                    "links",
                    models.ManyToManyField(
                        related_name="project_links", to="projects.link"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="project_tags", to="projects.tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legend", models.CharField(max_length=100)),
                ("legend_en", models.CharField(max_length=100, null=True)),
                ("legend_de", models.CharField(max_length=100, null=True)),
                ("legend_fr", models.CharField(max_length=100, null=True)),
                ("slug", models.SlugField()),
                (
                    "cover_picture",
                    models.BooleanField(default=False, verbose_name="cover picture"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="picture",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="picture visible on website"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_picture",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
