# Generated by Django 5.0.6 on 2024-09-20 15:45

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doridoro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("legend", models.CharField(max_length=100)),
                ("legend_en", models.CharField(max_length=100, null=True)),
                ("legend_de", models.CharField(max_length=100, null=True)),
                ("legend_fr", models.CharField(max_length=100, null=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("GITHUB", "GitHub"),
                            ("VERCEL", "Vercel"),
                            ("RENDER", "Render"),
                            ("OTHER", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("OPENCLASSROOMS", "OpenClasssrooms"),
                            ("PERSONAL_PROJECT", "Personal Project"),
                        ],
                        max_length=17,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="link visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50, null=True)),
                ("name_de", models.CharField(max_length=50, null=True)),
                ("name_fr", models.CharField(max_length=50, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROGRAMMING_SKILLS", "Programming Skills"),
                            ("SOFT_SKILLS", "Soft Skills"),
                            ("OTHER", "Other"),
                            ("STRENGTH", "Strength"),
                            ("WEAKNESSES", "Weakness"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="skill visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("OPENCLASSROOMS_PROJECT", "OpenClassrooms Project"),
                            ("PERSONAL_PROJECT", "Personal Project"),
                        ],
                        max_length=22,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="tag visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("title_en", models.CharField(max_length=250, null=True)),
                ("title_de", models.CharField(max_length=250, null=True)),
                ("title_fr", models.CharField(max_length=250, null=True)),
                ("slug", models.SlugField()),
                ("legend", models.CharField(max_length=100)),
                ("legend_en", models.CharField(max_length=100, null=True)),
                ("legend_de", models.CharField(max_length=100, null=True)),
                ("legend_fr", models.CharField(max_length=100, null=True)),
                ("create_date", models.DateField(verbose_name="create date")),
                (
                    "evaluation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="evaluation date"
                    ),
                ),
                ("keywords", tinymce.models.HTMLField()),
                ("keywords_en", tinymce.models.HTMLField(null=True)),
                ("keywords_de", tinymce.models.HTMLField(null=True)),
                ("keywords_fr", tinymce.models.HTMLField(null=True)),
                ("introduction", tinymce.models.HTMLField()),
                ("introduction_en", tinymce.models.HTMLField(null=True)),
                ("introduction_de", tinymce.models.HTMLField(null=True)),
                ("introduction_fr", tinymce.models.HTMLField(null=True)),
                ("experience", tinymce.models.HTMLField()),
                ("experience_en", tinymce.models.HTMLField(null=True)),
                ("experience_de", tinymce.models.HTMLField(null=True)),
                ("experience_fr", tinymce.models.HTMLField(null=True)),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="project visible on website"
                    ),
                ),
                (
                    "doridoro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doro_project",
                        to="doridoro.doridoro",
                    ),
                ),
                (
                    "links",
                    models.ManyToManyField(
                        related_name="project_links", to="projects.link"
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        related_name="project_skills", to="projects.skill"
                    ),
                ),
                (
                    "tags",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_tags",
                        to="projects.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legend", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                (
                    "cover_picture",
                    models.BooleanField(default=False, verbose_name="cover picture"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="picture",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="picture visible on website"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_picture",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
