# Generated by Django 5.0.6 on 2024-10-16 12:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="future",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="future_de",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="future_en",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="future_fr",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
