# Generated by Django 5.0.6 on 2024-10-16 15:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_project_future_project_future_de_project_future_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="cover_picture",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="picture",
            name="slug",
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name="project",
            name="create_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="evaluation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="future",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="future plans of project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="future_de",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="future plans of project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="future_en",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="future plans of project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="future_fr",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="future plans of project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="keywords",
            field=tinymce.models.HTMLField(verbose_name="skill set of project"),
        ),
        migrations.AlterField(
            model_name="project",
            name="keywords_de",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="skill set of project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="keywords_en",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="skill set of project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="keywords_fr",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="skill set of project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=250),
        ),
    ]
