# Generated by Django 6.0.4 on 2026-04-27 15:38

import django.db.models.deletion
import django.db.models.functions.text
import tinymce.models
import utils.database.slug
import utils.database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': [django.db.models.functions.text.Lower('name'), 'pk'],
                'indexes': [models.Index(django.db.models.functions.text.Lower('name'), models.F('active'), name='idx_contact_cat_name_active')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_contact_cat_lower_name', violation_error_code='unique', violation_error_message='The category name already exists.')],
            },
            bases=(utils.database.slug.SlugCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(max_length=200)),
                ('message', tinymce.models.HTMLField(validators=[utils.database.validators.validate_not_blank])),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contact.category')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['category', '-submitted_at'], name='idx_contact_category_submitted'), models.Index(django.db.models.functions.text.Lower('email'), django.db.models.functions.text.Lower('first_name'), name='idx_contact_first_name_email')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('first_name', ''), _negated=True), models.Q(('email', ''), _negated=True), models.Q(('subject', ''), _negated=True)), name='ck_contact_first_email', violation_error_code='check', violation_error_message='Your first name, the email address and the subject are required.')],
            },
        ),
    ]
