# Generated by Django 5.0.6 on 2025-11-09 11:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": [django.db.models.functions.text.Lower("name"), "pk"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="contactrequest",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Contact Request",
                "verbose_name_plural": "Contact Requests",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="published",
        ),
        migrations.AddField(
            model_name="category",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                verbose_name="contact category visible on website",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["name", "active"], name="idx_contact_name_active"
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["email", "submitted_at"], name="ix_email_submitted"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="uix_contact_cat_low_name",
            ),
        ),
    ]
