# Generated by Django 5.0.6 on 2024-09-28 08:07

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_de", models.CharField(max_length=100, null=True)),
                ("title_fr", models.CharField(max_length=100, null=True)),
                ("content", models.TextField()),
                ("content_en", models.TextField(null=True)),
                ("content_de", models.TextField(null=True)),
                ("content_fr", models.TextField(null=True)),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="achievement visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=100)),
                ("degree", models.CharField(max_length=100)),
                ("degree_en", models.CharField(max_length=100, null=True)),
                ("degree_de", models.CharField(max_length=100, null=True)),
                ("degree_fr", models.CharField(max_length=100, null=True)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="url of degree",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="degree visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_de", models.CharField(max_length=100, null=True)),
                ("title_fr", models.CharField(max_length=100, null=True)),
                ("content", models.TextField()),
                ("content_en", models.TextField(null=True)),
                ("content_de", models.TextField(null=True)),
                ("content_fr", models.TextField(null=True)),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="fact visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_de", models.CharField(max_length=100, null=True)),
                ("name_fr", models.CharField(max_length=100, null=True)),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="hobby visible on website"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "hobbies",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_name_en", models.CharField(max_length=200, null=True)),
                ("company_name_de", models.CharField(max_length=200, null=True)),
                ("company_name_fr", models.CharField(max_length=200, null=True)),
                ("position", models.CharField(max_length=200)),
                ("position_en", models.CharField(max_length=200, null=True)),
                ("position_de", models.CharField(max_length=200, null=True)),
                ("position_fr", models.CharField(max_length=200, null=True)),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "until_present",
                    models.BooleanField(default=False, verbose_name="until present"),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("address_en", models.CharField(blank=True, max_length=100, null=True)),
                ("address_de", models.CharField(blank=True, max_length=100, null=True)),
                ("address_fr", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FREELANCE", "Freelance"),
                            ("EMPLOYED", "Employed"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                            ("FORMATION", "Formation"),
                            ("MENTORING", "Mentoring"),
                            ("PARENTAL_LEAVE", "Parental_Leave"),
                            ("SABBATICAL", "Sabbatical"),
                        ],
                        max_length=14,
                        verbose_name="job type",
                    ),
                ),
                (
                    "job_type_en",
                    models.CharField(
                        choices=[
                            ("FREELANCE", "Freelance"),
                            ("EMPLOYED", "Employed"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                            ("FORMATION", "Formation"),
                            ("MENTORING", "Mentoring"),
                            ("PARENTAL_LEAVE", "Parental_Leave"),
                            ("SABBATICAL", "Sabbatical"),
                        ],
                        max_length=14,
                        null=True,
                        verbose_name="job type",
                    ),
                ),
                (
                    "job_type_de",
                    models.CharField(
                        choices=[
                            ("FREELANCE", "Freelance"),
                            ("EMPLOYED", "Employed"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                            ("FORMATION", "Formation"),
                            ("MENTORING", "Mentoring"),
                            ("PARENTAL_LEAVE", "Parental_Leave"),
                            ("SABBATICAL", "Sabbatical"),
                        ],
                        max_length=14,
                        null=True,
                        verbose_name="job type",
                    ),
                ),
                (
                    "job_type_fr",
                    models.CharField(
                        choices=[
                            ("FREELANCE", "Freelance"),
                            ("EMPLOYED", "Employed"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                            ("FORMATION", "Formation"),
                            ("MENTORING", "Mentoring"),
                            ("PARENTAL_LEAVE", "Parental_Leave"),
                            ("SABBATICAL", "Sabbatical"),
                        ],
                        max_length=14,
                        null=True,
                        verbose_name="job type",
                    ),
                ),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_de", models.TextField(null=True)),
                ("description_fr", models.TextField(null=True)),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="job visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50, null=True)),
                ("name_de", models.CharField(max_length=50, null=True)),
                ("name_fr", models.CharField(max_length=50, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Beginner"),
                            ("A2", "A2 - Elementary"),
                            ("B1", "B1 - Intermediate"),
                            ("B2", "B2 - Upper Intermediate"),
                            ("C1", "C1 - Advanced"),
                            ("C2", "C2 - Proficient"),
                            ("Native", "Native Speaker"),
                        ],
                        default="A1",
                        max_length=6,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="language visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("profession", models.CharField(max_length=250)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=14, null=True)),
                (
                    "language",
                    models.CharField(max_length=100, verbose_name="spoken language"),
                ),
                (
                    "language_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="spoken language"
                    ),
                ),
                (
                    "language_de",
                    models.CharField(
                        max_length=100, null=True, verbose_name="spoken language"
                    ),
                ),
                (
                    "language_fr",
                    models.CharField(
                        max_length=100, null=True, verbose_name="spoken language"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="reference visible on website"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "url",
                    models.URLField(max_length=250, verbose_name="url of social media"),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, verbose_name="social media visible on website"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SocialMedia",
            },
        ),
        migrations.CreateModel(
            name="DoriDoro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=14)),
                ("phone_en", models.CharField(max_length=14, null=True)),
                ("phone_de", models.CharField(max_length=14, null=True)),
                ("phone_fr", models.CharField(max_length=14, null=True)),
                ("address", models.CharField(max_length=150)),
                ("address_en", models.CharField(max_length=150, null=True)),
                ("address_de", models.CharField(max_length=150, null=True)),
                ("address_fr", models.CharField(max_length=150, null=True)),
                ("profession", models.CharField(max_length=150)),
                ("profession_en", models.CharField(max_length=150, null=True)),
                ("profession_de", models.CharField(max_length=150, null=True)),
                ("profession_fr", models.CharField(max_length=150, null=True)),
                ("introduction", tinymce.models.HTMLField()),
                ("introduction_en", tinymce.models.HTMLField(null=True)),
                ("introduction_de", tinymce.models.HTMLField(null=True)),
                ("introduction_fr", tinymce.models.HTMLField(null=True)),
                (
                    "dream_job",
                    tinymce.models.HTMLField(verbose_name="dream job description"),
                ),
                (
                    "dream_job_en",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="dream job description"
                    ),
                ),
                (
                    "dream_job_de",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="dream job description"
                    ),
                ),
                (
                    "dream_job_fr",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="dream job description"
                    ),
                ),
                (
                    "free_time",
                    tinymce.models.HTMLField(verbose_name="after work description"),
                ),
                (
                    "free_time_en",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="after work description"
                    ),
                ),
                (
                    "free_time_de",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="after work description"
                    ),
                ),
                (
                    "free_time_fr",
                    tinymce.models.HTMLField(
                        null=True, verbose_name="after work description"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doro_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user instance",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DoriDoro",
            },
        ),
    ]
