# Generated by Django 6.0.4 on 2026-04-29 11:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("title_en", models.CharField(max_length=300, null=True)),
                ("title_de", models.CharField(max_length=300, null=True)),
                ("title_fr", models.CharField(max_length=300, null=True)),
                ("content", models.CharField(max_length=500)),
                ("content_en", models.CharField(max_length=500, null=True)),
                ("content_de", models.CharField(max_length=500, null=True)),
                ("content_fr", models.CharField(max_length=500, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("title"), "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("title"),
                        name="uq_achieve_low_title",
                        violation_error_code="unique",
                        violation_error_message="An achievement already exists.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=100)),
                ("degree", models.CharField(max_length=100)),
                ("degree_en", models.CharField(max_length=100, null=True)),
                ("degree_de", models.CharField(max_length=100, null=True)),
                ("degree_fr", models.CharField(max_length=100, null=True)),
                ("url", models.URLField(blank=True, default="", max_length=250)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("organization"),
                    "pk",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("organization"),
                        django.db.models.functions.text.Lower("degree"),
                        name="uq_degree_low_orga_degree",
                        violation_error_code="unique",
                        violation_error_message="This organization-degree combination exists already.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50, null=True)),
                ("name_de", models.CharField(max_length=50, null=True)),
                ("name_fr", models.CharField(max_length=50, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Beginner"),
                            ("A2", "A2 - Elementary"),
                            ("B1", "B1 - Intermediate"),
                            ("B2", "B2 - Upper Intermediate"),
                            ("C1", "C1 - Advanced"),
                            ("C2", "C2 - Proficient"),
                            ("Native", "Native Speaker"),
                        ],
                        default="A1",
                        max_length=6,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name"), "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uix_lang_low_name",
                        violation_error_code="unique",
                        violation_error_message="This language already exists.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "level__in",
                                ["A1", "A2", "B1", "B2", "C1", "C2", "Native"],
                            )
                        ),
                        name="ck_lang_level_valid",
                        violation_error_code="check",
                        violation_error_message="This language level does not exist.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("url", models.URLField(max_length=250)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Social Media",
                "ordering": [django.db.models.functions.text.Lower("name"), "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uix_social_media_low_name",
                        violation_error_code="unique",
                        violation_error_message="This social media already exists.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("address", models.CharField(blank=True, default="", max_length=100)),
                (
                    "address_en",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "address_de",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "address_fr",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("position", models.CharField(max_length=200)),
                ("position_en", models.CharField(max_length=200, null=True)),
                ("position_de", models.CharField(max_length=200, null=True)),
                ("position_fr", models.CharField(max_length=200, null=True)),
                ("description", models.JSONField(default=list)),
                ("description_en", models.JSONField(default=list, null=True)),
                ("description_de", models.JSONField(default=list, null=True)),
                ("description_fr", models.JSONField(default=list, null=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FREELANCE", "Freelance"),
                            ("EMPLOYED", "Employed"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                            ("FORMATION", "Formation"),
                            ("MENTORING", "Mentoring"),
                            ("PARENTAL_LEAVE", "Parental Leave"),
                            ("SABBATICAL", "Sabbatical"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("ON_SITE", "On site"),
                            ("HYBRID", "Hybrid"),
                            ("REMOTE", "Remote"),
                        ],
                        max_length=7,
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "until_present",
                    models.BooleanField(default=False, verbose_name="present"),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "links",
                    models.ManyToManyField(related_name="jobs", to="projects.link"),
                ),
                (
                    "skill",
                    models.ManyToManyField(related_name="jobs", to="projects.skill"),
                ),
            ],
            options={
                "ordering": ["start_date", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("position"),
                        django.db.models.functions.text.Lower("company_name"),
                        models.F("start_date"),
                        name="uq_job_position_company_start",
                        violation_error_code="unique",
                        violation_error_message="This position-company-start combination exists already.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("until_present", True),
                            ("end_date__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_job_present_end",
                        violation_error_code="check",
                        violation_error_message="End date must be provided if the job is not ongoing.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("until_present", True), _negated=True),
                            ("end_date__isnull", True),
                            _connector="OR",
                        ),
                        name="ck_job_present_no_end",
                        violation_error_code="check",
                        violation_error_message="If the job is ongoing, the end date should be empty.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "job_type__in",
                                [
                                    "FREELANCE",
                                    "EMPLOYED",
                                    "APPRENTICESHIP",
                                    "FORMATION",
                                    "MENTORING",
                                    "PARENTAL_LEAVE",
                                    "SABBATICAL",
                                ],
                            )
                        ),
                        name="ck_job_type",
                        violation_error_code="check",
                        violation_error_message="This job type does not exist.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "job_type__in",
                                    ["EMPLOYED", "APPRENTICESHIP", "FORMATION"],
                                ),
                                _negated=True,
                            ),
                            ("company_name__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_job_selected_type_company",
                        violation_error_code="check",
                        violation_error_message="With this job_type a company_name has to be filled out.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__gte", models.F("start_date")),
                            ("end_date__isnull", True),
                            _connector="OR",
                        ),
                        name="ck_job_start_before_end",
                        violation_error_code="check",
                        violation_error_message="End date should be after start date.",
                    ),
                ],
            },
        ),
    ]
