# Generated by Django 5.0.6 on 2024-06-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doridoro", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.ManyToManyField(
                related_name="job_tags",
                to="projects.tag",
                verbose_name="tags of the job",
            ),
        ),
    ]
