# Generated by Django 5.0.6 on 2024-10-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doridoro", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_name_de",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_name_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_name_fr",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
