# Generated by Django 5.0.6 on 2024-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doridoro", "0003_alter_job_company_name_alter_job_company_name_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="url",
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="until_present",
            field=models.BooleanField(default=False, verbose_name="present"),
        ),
    ]
